[package]
name = "mopac_gpu"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "High-Performance Direct Vulkan GPU Compute Acceleration for MOPAC_RS"

[dependencies]
ash = "0.38"
mopac_core = { path = "../mopac_core" }
