[package]
name = "mopac"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Canonical Command-Line Interface (CLI) binary for MOPAC_RS"
readme = "../../README.md"

[[bin]]
name = "mopac"
path = "src/main.rs"

[dependencies]
mopac_core = { path = "../mopac_core", version = "0.1.0" }
mopac_gpu = { path = "../mopac_gpu", version = "0.1.0" }
clap = { version = "4.5", features = ["derive"] }
rayon = "1.10"
