//! Structure-Data File (SDF / MOL V2000) and Multi-Model Trajectory Serializer.
//!
//! Formats molecular coordinates, topology, bond orders, and dynamic relaxation
//! trajectories for visualization in Molstar and cheminformatics pipelines.
//!
//! Licensed under the Apache License, Version 2.0 (the "License").

use crate::types::AlignedMatrix;

/// Maps atomic number (1..118) to standard IUPAC elemental symbol.
pub fn z_to_symbol(z: u8) -> &'static str {
    match z {
        1 => "H",
        2 => "He",
        3 => "Li",
        4 => "Be",
        5 => "B",
        6 => "C",
        7 => "N",
        8 => "O",
        9 => "F",
        10 => "Ne",
        11 => "Na",
        12 => "Mg",
        13 => "Al",
        14 => "Si",
        15 => "P",
        16 => "S",
        17 => "Cl",
        18 => "Ar",
        19 => "K",
        20 => "Ca",
        21 => "Sc",
        22 => "Ti",
        23 => "V",
        24 => "Cr",
        25 => "Mn",
        26 => "Fe",
        27 => "Co",
        28 => "Ni",
        29 => "Cu",
        30 => "Zn",
        31 => "Ga",
        32 => "Ge",
        33 => "As",
        34 => "Se",
        35 => "Br",
        36 => "Kr",
        46 => "Pd",
        47 => "Ag",
        50 => "Sn",
        53 => "I",
        78 => "Pt",
        79 => "Au",
        80 => "Hg",
        82 => "Pb",
        _ => "X",
    }
}

use crate::corrections::h_bonds4::covalent_radius;

/// Inferred molecular bond between two atoms (1-indexed for SDF).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MolBond {
    pub atom1: usize,
    pub atom2: usize,
    pub order: u8, // 1 = Single, 2 = Double, 3 = Triple, 4 = Aromatic
}

/// Infer molecular bonds using Mayer bond order matrix or covalent distance heuristic.
pub fn infer_bonds(
    atomic_numbers: &[u8],
    coords: &[[f64; 3]],
    mayer_bond_orders: Option<&AlignedMatrix<f64>>,
) -> Vec<MolBond> {
    let natoms = atomic_numbers.len();
    let mut bonds = Vec::new();

    if let Some(mbo) = mayer_bond_orders {
        for a in 0..natoms {
            for b in (a + 1)..natoms {
                let bo = mbo.get(a, b);
                if bo >= 0.45 {
                    let order = if bo >= 2.6 {
                        3
                    } else if bo >= 1.6 {
                        2
                    } else if bo >= 1.25 {
                        4 // Aromatic
                    } else {
                        1
                    };
                    bonds.push(MolBond {
                        atom1: a + 1,
                        atom2: b + 1,
                        order,
                    });
                }
            }
        }
    } else {
        // Covalent radii thresholding with 0.45 A tolerance
        for a in 0..natoms {
            let ra = covalent_radius(atomic_numbers[a]);
            for b in (a + 1)..natoms {
                let rb = covalent_radius(atomic_numbers[b]);
                let max_d = ra + rb + 0.45;
                let dx = coords[a][0] - coords[b][0];
                let dy = coords[a][1] - coords[b][1];
                let dz = coords[a][2] - coords[b][2];
                let dist = (dx * dx + dy * dy + dz * dz).sqrt();
                if dist > 0.4 && dist <= max_d {
                    bonds.push(MolBond {
                        atom1: a + 1,
                        atom2: b + 1,
                        order: 1,
                    });
                }
            }
        }
    }

    bonds
}

/// Format molecular structure as an MDL Molfile / SDF V2000 block string.
pub fn export_sdf_v2000(
    atomic_numbers: &[u8],
    coords: &[[f64; 3]],
    title: &str,
    properties: &[(&str, &str)],
    mayer_bond_orders: Option<&AlignedMatrix<f64>>,
) -> String {
    let natoms = atomic_numbers.len();
    let bonds = infer_bonds(atomic_numbers, coords, mayer_bond_orders);
    let nbonds = bonds.len();

    let mut out = String::with_capacity(1024 + natoms * 80 + nbonds * 30);

    // Line 1: Title
    out.push_str(title);
    out.push('\n');

    // Line 2: Program generator info
    out.push_str("  MOPAC_RS0.1.1                 3D\n");

    // Line 3: Comments
    out.push_str("Quantum Chemical Structure Generated by mopac_rs\n");

    // Counts line: aaabbblllfffcccsssxxxrrrpppiiimmmvvvvvv
    // natoms (3), nbonds (3), 0 0 0 0 0 0 0 0999 V2000
    out.push_str(&format!(
        "{:3}{:3}  0  0  0  0  0  0  0  0999 V2000\n",
        natoms, nbonds
    ));

    // Atom block: x(10.4) y(10.4) z(10.4) symbol(3) mass_diff(2) charge(3) ...
    for i in 0..natoms {
        let sym = z_to_symbol(atomic_numbers[i]);
        let x = coords[i][0];
        let y = coords[i][1];
        let z = coords[i][2];
        out.push_str(&format!(
            "{:10.4}{:10.4}{:10.4} {:3} 0  0  0  0  0  0  0  0  0  0  0  0\n",
            x, y, z, sym
        ));
    }

    // Bond block: 111222tttsssxxxrrrccc
    for bond in &bonds {
        out.push_str(&format!(
            "{:3}{:3}{:3}  0  0  0  0\n",
            bond.atom1, bond.atom2, bond.order
        ));
    }

    // End of Molfile structure
    out.push_str("M  END\n");

    // SDF Data Fields (Properties)
    for (key, val) in properties {
        out.push_str(&format!("> <{}>\n{}\n\n", key, val));
    }

    // SDF Record Terminator
    out.push_str("$$$$\n");

    out
}

/// Format multi-model trajectory as a standard multi-frame XYZ string.
///
/// Molstar natively detects multi-frame XYZ files, loads them as animated
/// trajectories, and displays playback controls (Play, Pause, Scrub).
pub fn export_trajectory_xyz(
    atomic_numbers: &[u8],
    frames: &[Vec<[f64; 3]>],
    frame_comments: &[String],
) -> String {
    let natoms = atomic_numbers.len();
    let mut out = String::with_capacity(frames.len() * (natoms * 60 + 50));

    for (i, frame) in frames.iter().enumerate() {
        // 1. Number of atoms
        out.push_str(&format!("{}\n", natoms));

        // 2. Comment line (Frame index, Energy, RMS Gradient)
        if i < frame_comments.len() {
            out.push_str(&frame_comments[i]);
        } else {
            out.push_str(&format!("Model {} Generated by mopac_rs", i + 1));
        }
        out.push('\n');

        // 3. Atom coordinates
        for a in 0..natoms {
            let sym = z_to_symbol(atomic_numbers[a]);
            let x = frame[a][0];
            let y = frame[a][1];
            let z = frame[a][2];
            out.push_str(&format!("{:2}  {:14.6}  {:14.6}  {:14.6}\n", sym, x, y, z));
        }
    }

    out
}

/// Format multi-model trajectory as a concatenated SDF file.
pub fn export_trajectory_sdf(
    atomic_numbers: &[u8],
    frames: &[Vec<[f64; 3]>],
    titles: &[String],
    properties_per_frame: &[Vec<(&str, String)>],
) -> String {
    let mut out = String::new();
    for (i, frame) in frames.iter().enumerate() {
        let title = if i < titles.len() {
            &titles[i]
        } else {
            "MOPAC_RS Trajectory Frame"
        };
        let props_vec = if i < properties_per_frame.len() {
            properties_per_frame[i]
                .iter()
                .map(|(k, v)| (*k, v.as_str()))
                .collect::<Vec<_>>()
        } else {
            Vec::new()
        };
        let sdf_frame = export_sdf_v2000(atomic_numbers, frame, title, &props_vec, None);
        out.push_str(&sdf_frame);
    }
    out
}
